/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATree: typeof import('ant-design-vue/es')['Tree']
    Beng: typeof import('./src/components/device-windows/beng.vue')['default']
    CaretDownOutlined: typeof import('@ant-design/icons-vue')['CaretDownOutlined']
    CaretLeftOutlined: typeof import('@ant-design/icons-vue')['CaretLeftOutlined']
    CaretRightOutlined: typeof import('@ant-design/icons-vue')['CaretRightOutlined']
    CaretUpOutlined: typeof import('@ant-design/icons-vue')['CaretUpOutlined']
    ChiTang: typeof import('./src/components/land-panel/ChiTang.vue')['default']
    Diancifa: typeof import('./src/components/device-windows/diancifa.vue')['default']
    DvTable: typeof import('./src/components/DvTable/index.vue')['default']
    EasyPlayer: typeof import('./src/components/EasyPlayer/index.vue')['default']
    Empty: typeof import('./src/components/Video/empty.vue')['default']
    GeTian: typeof import('./src/components/land-panel/GeTian.vue')['default']
    HanTian: typeof import('./src/components/land-panel/HanTian.vue')['default']
    IndicatorItem: typeof import('./src/components/IndicatorItem/index.vue')['default']
    InfoWindow: typeof import('./src/components/InfoWindow/index.vue')['default']
    Jixieshuibiao: typeof import('./src/components/device-windows/jixieshuibiao.vue')['default']
    Map: typeof import('./src/components/map/Map.vue')['default']
    MapLegend: typeof import('./src/components/map/MapLegend.vue')['default']
    MapPopup: typeof import('./src/components/map/MapPopup.vue')['default']
    NoticeWeek: typeof import('./src/components/map/NoticeWeek.vue')['default']
    PuTongDaPeng: typeof import('./src/components/land-panel/PuTongDaPeng.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaleBox: typeof import('./src/components/ScaleBox/index.vue')['default']
    Select: typeof import('./src/components/Select/index.vue')['default']
    SettingOutlined: typeof import('@ant-design/icons-vue')['SettingOutlined']
    ShuiTian: typeof import('./src/components/land-panel/ShuiTian.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    Switch: typeof import('./src/components/Switch/index.vue')['default']
    Table: typeof import('./src/components/Table/index.vue')['default']
    Tianjianshuiweizhan: typeof import('./src/components/device-windows/tianjianshuiweizhan.vue')['default']
    Video: typeof import('./src/components/Video/index.vue')['default']
    Yuanchuanshuibiao: typeof import('./src/components/device-windows/yuanchuanshuibiao.vue')['default']
  }
}
